version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=pa
      - POSTGRES_USER=pa
      - POSTGRES_PASSWORD=papa
    ports:
      - "5001:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  db_test:  # TODO separate docker-compose override for tests
    image: postgres
    environment:
      - POSTGRES_DB=pa
      - POSTGRES_USER=pa
      - POSTGRES_PASSWORD=papa
    ports:
      - "5002:5432"
  productaggregator:
    build: src/productaggregator
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app:create_app('DevelopmentConfig')
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./src/productaggregator:/usr/src/app
    depends_on:
      - db
      - db_test
    restart: on-failure  # if flask db upgrade is run before db created
volumes:
  db-data:
