"""empty message

Revision ID: 533b2f454f80
Revises: c64aa56f319d
Create Date: 2020-08-28 20:48:17.822197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533b2f454f80'
down_revision = 'c64aa56f319d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_name_key', 'product', type_='unique')
    op.create_unique_constraint(None, 'product', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.create_unique_constraint('product_name_key', 'product', ['name'])
    # ### end Alembic commands ###
