"""empty message

Revision ID: c64aa56f319d
Revises: 1eaf4fcc6af0
Create Date: 2020-08-28 20:45:32.828999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c64aa56f319d'
down_revision = '1eaf4fcc6af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_uuid_key', 'product', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('product_uuid_key', 'product', ['uuid'])
    # ### end Alembic commands ###
