"""empty message

Revision ID: ecfe7c08f1c7
Revises: 533b2f454f80
Create Date: 2020-08-30 10:53:12.072886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecfe7c08f1c7'
down_revision = '533b2f454f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('offer', sa.Column('id_external', sa.Integer(), nullable=False))
    op.add_column('offer', sa.Column('offers_batch_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('_id_external_product_batch_uc', 'offer', ['product_id', 'id_external', 'offers_batch_id'])
    op.create_foreign_key(None, 'offer', 'offers_batch', ['offers_batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.drop_constraint('_id_external_product_batch_uc', 'offer', type_='unique')
    op.drop_column('offer', 'offers_batch_id')
    op.drop_column('offer', 'id_external')
    op.drop_table('offers_batch')
    # ### end Alembic commands ###
